name: "Deploy"

on:
  push:
    branches:
      - dev*
      - test
      - prod

# required environment variables
env:
  SUBSCRIPTION_ID: abcfb30c-2430-42eb-9745-82bfee455fef
  REGION: southcentralus
  PREFIX: pn

jobs:
  check-bicep:
    name: Build - check bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build bicep and check for errors
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            for FILE in ./templates/*.bicep; do
              echo $FILE
              # bicep build $FILE
            done

  main-deploy:
    name: Main Deploy
    runs-on: ubuntu-latest
    steps:
      # get set BRANCH variable with branch name to be used in resource naming
      - name: Set env.BRANCH 
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create resource groups
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            for FILE in ./templates/*.bicep; do
            echo $FILE
            # az group create --name "${{ env.PREFIX }}-${{ env.BRANCH }}-bootstrap1-${{ env.REGION }}-rg" --location ${{ env.REGION }}
      # - name: Deploy resources
      #   uses: Azure/arm-deploy@v1
      #   with:
      #     scope: subscription
      #     subscriptionId: ${{ env.SUBSCRIPTION_ID }}
      #     region: ${{ env.REGION }}
      #     deploymentMode: Complete
      #     template: ./templates/00maindeploy.bicep
      #     parameters:
      #       BRANCH=${{ env.BRANCH }}
      #       REGION=${{ env.REGION }}
      #       PREFIX=${{ env.PREFIX }}