name: "Deploy to Azure"

on:
  push:
    branches:
      - test
      - prod
      - dev
      - dev2

env:
  SUBSCRIPTION_ID: "f7741b3d-d2ac-4be0-8083-e8dc60675c97"
  LOCATION: southcentralus

jobs:
  GitHub-Actions-Test:
    name: GitHub Actions Test #1
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG - see GITHUB_REF
        run: echo "variable ${GITHUB_REF}"

      # extract branch name into GitHub environment BRANCH
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "This is ${{ env.BRANCH }}"
        id: extract_branch

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2
      
      - run: az account show -o table

      - name: Deploy resource group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          deploymentMode: Complete
          template: ./modules/resourcegroup.bicep
          parameters:
            RG_NAME="${{ env.BRANCH }}-launchpad-${{ env.LOCATION }}-rg"
            BRANCH="${{ env.BRANCH }}"
            LOCATION=${{ env.LOCATION }}