name: "Deploy to Azure"

on:
  push:
    branches:
      - test
      - prod
      - dev2
  pull_request:
    branches:
      - test
      - prod

env:
  SUBSCRIPTION_ID: "f7741b3d-d2ac-4be0-8083-e8dc60675c97"
  REGION: southcentralus

jobs:
  Deploy-to-Azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG - see GITHUB_REF
        run: echo "variable ${GITHUB_REF}"

      # extract branch name into GitHub environment BRANCH
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      # DEBUG: show branch name
      - name: DEBUG - Extract branch name
        shell: bash
        run: echo "This is ${{ env.BRANCH }}"
        id: extract_branch

      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az account show -o table

      - name: Deploy resource groups
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          region: ${{ env.REGION }}
          # deploymentMode: Complete
          template: ./templates/01-resourcegroups.bicep
          parameters:
            BRANCH="${{ env.BRANCH }}"
            REGION=${{ env.REGION }}