name: "Deploy to Azure"

on:
  push:
    branches:
      - test
      - prod
      - dev
      - dev2

env:
  SUBSCRIPTION_ID: "f7741b3d-d2ac-4be0-8083-e8dc60675c97"

jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "variable ${GITHUB_REF}"

      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "This is ${{ env.BRANCH }}"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: az account show -o table