name: "Deploy to Azure"

on:
  push:
    branches:
      - test
      - main

env:
  subscriptionId: "f7741b3d-d2ac-4be0-8083-e8dc60675c97"

jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github action run 1"