name: "Deploy to Azure"

on:
  push:
    branches:
      - test
      - prod

env:
  SUBSCRIPTION_ID: "f7741b3d-d2ac-4be0-8083-e8dc60675c97"

jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Subscription ID ${SUBSCRIPTION_ID}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: az account show