name: "Destroy branch"

on:
  workflow_dispatch:

env:
  SUBSCRIPTION_ID: f7741b3d-d2ac-4be0-8083-e8dc60675c97
  REGION: southcentralus

jobs:
  Destroy-Branch:
    name: Destroy branch environment
    runs-on: ubuntu-latest

    steps:
      # extract branch name into GitHub environment BRANCH
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Destroy resource groups
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az group delete --subscription ${{ env.SUBSCRIPTION_ID }} --name ${{ env.BRANCH }}-launchpad-${{ env.REGION }}-rg